name       : gnome-font-viewer
version    : '44.0'
release    : 21
source     :
    - https://download.gnome.org/sources/gnome-font-viewer/44/gnome-font-viewer-44.0.tar.xz : a1511df30b228cc2ef1175dd9d2b93438ea912e25913404b263cf3d457bb9f97
homepage   : https://gitlab.gnome.org/GNOME/gnome-font-viewer/
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : A font viewer utility for GNOME
description: |
    Shows a preview of fonts and an overview of all installed fonts.
builddeps  :
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(harfbuzz)
    - pkgconfig(libadwaita-1)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
