name       : gnome-font-viewer
version    : '42.0'
release    : 18
source     :
    - https://download.gnome.org/sources/gnome-font-viewer/42/gnome-font-viewer-42.0.tar.xz : cfa2b8dfff21a105a1a021dadfa213f13627e6a179a77c7b59fdcedaca848dcc
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Font Viewer
description: |
    Gnome Font Viewer
builddeps  :
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(harfbuzz)
    - pkgconfig(libadwaita-1)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
