name       : gnome-font-viewer
version    : 3.16.2
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-font-viewer/3.16/gnome-font-viewer-3.16.2.tar.xz : f5367417d926d1dbe175aceb8eb4d2733d723a237428f130edd4b4023c0dc1cf
license    : GPL-2.0
summary    : Gnome Font Viewer
description: |
    Gnome Font Viewer
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(harfbuzz)
    - pkgconfig(gnome-desktop-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
