name       : gnome-font-viewer
version    : 3.32.0
release    : 10
source     :
    - https://download.gnome.org/sources/gnome-font-viewer/3.32/gnome-font-viewer-3.32.0.tar.xz : 43e1b0e759882d3597e650eb043e3d89c64cff9c124ceb6889e1a4a134286181
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Font Viewer
description: |
    Gnome Font Viewer
builddeps  :
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(harfbuzz)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
