name       : gnome-font-viewer
version    : 3.34.0
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-font-viewer/3.34/gnome-font-viewer-3.34.0.tar.xz : aa6f0583e5f93aec095e537f0638b29de3d02491f0131ef584a7c55d39d6b98b
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Font Viewer
description: |
    Gnome Font Viewer
builddeps  :
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(harfbuzz)
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
