name       : gnome-font-viewer
version    : 3.20.2
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-font-viewer/3.20/gnome-font-viewer-3.20.2.tar.xz : c95b336c15fade23ce239087897d91abcd3ae3776cd15b0c71321629a94abe8e
license    : GPL-2.0
summary    : Gnome Font Viewer
description: |
    Gnome Font Viewer
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(harfbuzz)
    - pkgconfig(gnome-desktop-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
